import 'package:eventek_layth/model/list_view_model.dart';
import 'package:eventek_layth/screen_three/widget/list_view_item.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class ScreenThree extends StatelessWidget {
  const ScreenThree({super.key});

  @override
  Widget build(BuildContext context) {
    List<ListViewModel> list = [
      ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),
      ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),  ListViewModel(iconData: Icons.people, text: 'Friends'),
      ListViewModel(iconData: Icons.stacked_bar_chart, text: 'Statistics'),
      ListViewModel(iconData: Icons.book, text: 'Academy'),
      ListViewModel(iconData: Icons.music_note_rounded, text: 'Music'),
      ListViewModel(iconData: Icons.person, text: 'Body'),
    ];
    return Scaffold(
      appBar: AppBar(
        leading: const Icon(Icons.arrow_back_ios),
        title: const Text(
          'Profile',
          style: TextStyle(
            fontSize: 22,
            fontWeight: FontWeight.bold,
          ),
        ),
        centerTitle: true,
        actions: [
          IconButton(
              onPressed: () {}, icon: const Icon(Icons.bookmark_border_rounded))
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.only(
          left: 20.0,
          right: 20,
          top: 8,
        ),
        child: SingleChildScrollView(
          child: Column(
            children: [
              const CircleAvatar(
                radius: 50,
                backgroundImage:AssetImage('assets/images/yousef_image.jpg') ,
              ),
              const Text(
                'Yousef Blaawe',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
              ),
              const Text(
                'Mobile Developer',
                style: TextStyle(height: 1),
              ),
              const SizedBox(
                height: 30,
              ),
              Container(
                padding: const EdgeInsets.all(8),
                width: double.infinity,
                height: 70,
                decoration: BoxDecoration(
                    color: Colors.grey[400],
                    borderRadius: BorderRadius.circular(20)),
                child: const Row(
                  children: [
                    Icon(
                      Icons.directions_walk,
                      size: 30,
                    ),
                    SizedBox(
                      width: 10,
                    ),
                    Text(
                      '665852',
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 22),
                    ),
                    Spacer(),
                    Text(
                      'Steps Today',
                      style: TextStyle(fontWeight: FontWeight.w900),
                    )
                  ],
                ),
              ),
              const SizedBox(
                height: 20,
              ),
              ListView.separated(
                physics: NeverScrollableScrollPhysics(),
                  shrinkWrap: true,
                  itemBuilder: (context, index) {
                    return ListViewItem(
                      text: list[index].text,
                      iconData: list[index].iconData,
                    );
                  },
                  separatorBuilder: (context, index) {
                    return const SizedBox(
                      height: 10,
                    );
                  },
                  itemCount: list.length)
            ],
          ),
        ),
      ),
    );
  }
}
